### ISSUE TITLE
Issues while loading function

### ISSUE THREAD

**Issue by nitishpanchpor** [chaitanyagupta/cowin#1]
Hi,
I am no expert in LISP but I have installed sbcl and ql.
But Not sure why while running script I am getting 
caught STYLE-WARNING:
;   undefined function: COMMON-LISP-USER::AVAILABLE-CENTERS

;     (GET-CENTERS "08-05-2021" :DISTRICT-NAME "Gurgaon")
; 
; caught STYLE-WARNING:
;   undefined function: COMMON-LISP-USER::GET-CENTERS
; 
; compilation unit finished
;   Undefined functions:
;     AVAILABLE-CENTERS GET-CENTERS
;   caught 2 STYLE-WARNING conditions

Can you help me in setting up script

Thanks
appreciate your efforts

**Comment by chaitanyagupta** [comment]
Sorry. Just run `(in-package :cowin)` before you run any of the Lisp functions.

**Comment by chaitanyagupta** [comment]
Update the README with this instruction.

**Comment by nitishpanchpor** [comment]
@chaitanyagupta tried the instructions but getting following error

The name "COWIN" does not designate any package.

**Comment by nitishpanchpor** [comment]
Thanks, Chaitanya. Can you add some more use cases like multiple centres.

**Comment by chaitanyagupta** [comment]
Sorry, you'll have to figure that out on your own.
